### ISSUE TITLE
something wrong with display

### ISSUE THREAD

**Issue by chencgln** [jojolebarjos/implicit-skinning#1]
Hello, I've installed the libs(glfw3, openmesh and glm), and compiled the cpp code on my ubuntu14. But when I run this code, it seems to works but there is something wrong with diapaly, as the following figure shows:
![screenshot from 2016-12-16 16 14 47](https://cloud.githubusercontent.com/assets/11676956/21268334/4187e516-c3e9-11e6-9ed7-5d36809ea8df.png)

So, I wonder if I have missed somthing. And do you have any idea on this?

Thank you for your time!

**Comment by jojolebarjos** [comment]
This kind of issue is usually due to shader compilation errors. OpenGL 3.3 is required for this demo, please check if your driver supports it. You may be able to modify the code to run it on OpenGL 2.0, although you will have to disable multisampling.

**Comment by chencgln** [comment]
Hello, here is the environment and Opengl information:

![screenshot from 2016-12-21 10 59 55](https://cloud.githubusercontent.com/assets/11676956/21376057/fc7eb1de-c76c-11e6-9275-a93216e1e5d7.png)

is there something wrong with it?

**Comment by jojolebarjos** [comment]
I have added a debug callback, so you should be able to have more detailed informations about the issue. As I said, this is probably an error during shader compilation. We did not thoroughly test on multiple platforms.

**Comment by aitmouhou** [comment]
how can i compile it under windows / think you

**Comment by jojolebarjos** [comment]
You can use [Mingw-w64](https://mingw-w64.org/doku.php). You will need to build [GLEW](http://glew.sourceforge.net/) and [GLFW](https://www.glfw.org/) from source, though.

**Comment by aitmouhou** [comment]
thinks
